version: '3.4'

services:
  web:
    image: dangcuuson
    working_dir: /usr/src/app/packages/dcs-web
    command: yarn start
    ports:
      - "3000:3000"
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile.dev
    environment:
      NODE_ENV: development
    develop:
      watch:
        - action: sync
          # context dir is where this yml file located. It has no relation to workdiing_dir
          # Not sure how to set it to watch multiple folder using wildcard
          path: ../packages
          target: /usr/src/app/packages
          ignore:
            - node_modules/
        # no need as I thikn it's better to rebuild image manually after package installation
        #- action: rebuild
        #  path: ../package.json
